IHIConfig/Controllers/ConfiguracionController.cs
using IHIConfig.Filtros;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Intecsus.Entidades;

namespace IHIConfig.Controllers
{
    [Loging(Order = 1)]
    [LogErrors(Order = 2)]
    [HandleError(Order = 3)]
    public class ConfiguracionController : Controller
    {
        // GET: Configuracion
        public ActionResult Index()
        {
            List<Configurar> m_ListConfigurar = new List<Configurar>();
            //Capa negocio
            Configurar m_Config = new Configurar
            {
                IDValor = "1",
                Valor = "Pruebas",
                TipoDato = "Cadena"
            };
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            ViewBag.ListaConfig = m_ListConfigurar;
            return View("Index");
        }

        // GET: Configuracion/Details
        public PartialViewResult Details(Configurar configurar)
        {
            ViewBag.ConfigIHI = "Modificar";
            return PartialView("_Create", configurar);
        }

        // GET: Configuracion/Create
        public PartialViewResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public PartialViewResult Crear(Configurar config)
        {
            //OPTIMIZAR y validar si viene vacio para no ejecutar la operacion
            List<Configurar> m_Configs = new List<Configurar>();
            Configurar m_Config = new Configurar
            {
                IDValor = "1",
                Valor = "Pruebas Creacion",
                TipoDato = "Cadena"
            };
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            ViewBag.ListaConfig = m_Configs;
            ViewBag.MensajeSuccess = "Parametro de configuración Creado";
            return PartialView("Index");
        }

        [HttpPost]
        public PartialViewResult Modificar(Configurar config)
        {
            //OPTIMIZAR
            List<Configurar> m_Configs = new List<Configurar>();
            Configurar m_Config = new Configurar
            {
                IDValor = "1",
                Valor = "Pruebas Edición",
                TipoDato = "Cadena"
            };
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            ViewBag.ListaConfig = m_Configs;
            ViewBag.MensajeSuccess = "Parametro de configuración Modificado";
            return PartialView("Index");
        }

        [HttpPost]
        public PartialViewResult Delete(int idConfig)
        {
            //OPTIMIZAR
            List<Configurar> m_Configs = new List<Configurar>();
            Configurar m_Config = new Configurar
            {
                IDValor = "1",
                Valor = "Pruebas Eliminacion",
                TipoDato = "Cadena"
            };
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            ViewBag.ListaConfig = m_Configs;
            ViewBag.MensajeSuccess = "Parametro de configuración Eliminado";
            ViewBag.Informativo = "Se aconseja NO eliminar los parametros ya que afectara el funcionamiento del IHI";
            return PartialView("Index");
        }
    }
}

IHIConfig/Controllers/RolController.cs
using IHIConfig.Filtros;
using Intecsus.Entidades;
using System.Collections.Generic;
using System.Web.Mvc;

namespace IHIConfig.Controllers
{
    [Loging(Order = 1)]
    [LogErrors(Order = 2)]
    [HandleError(Order = 3)]
    public class RolController : Controller
    {
        // GET: Rol
        public ActionResult Index()
        {
            UsuarioC m_User = (UsuarioC)Session["Usuario"];
            ViewBag.ListRoles = m_User.Roles;
            return View("Index");
        }

        // GET: Configuracion/Details
        public PartialViewResult Details(Rol rol)
        {
            ViewBag.Rol = "Modificar";
            return PartialView("_Create", rol);
        }

        // GET: Configuracion/Create
        public PartialViewResult Create()
        {
            return PartialView("_Create");
        }


        [HttpPost]
        public PartialViewResult Crear(Rol rol)
        {
            //OPTIMIZAR y validar si viene vacio para no ejecutar la operacion
            List<Rol> m_Roles = new List<Rol>();

            m_Roles.Add(rol);
            m_Roles.Add(rol);
            m_Roles.Add(rol);
            ViewBag.ListaRoles = m_Roles;
            ViewBag.MensajeSuccess = "Rol Creado";
            return PartialView("Index");
        }

        [HttpPost]
        public PartialViewResult Modificar(Rol rol)
        {
            //OPTIMIZAR
            List<Rol> m_Roles = new List<Rol>();

            m_Roles.Add(rol);
            m_Roles.Add(rol);
            m_Roles.Add(rol);
            ViewBag.ListaRoles = m_Roles;
            ViewBag.MensajeSuccess = "Rol Modificado";
            return PartialView("Index");
        }

        [HttpPost]
        public PartialViewResult Delete(int idRol)
        {
            //OPTIMIZAR
            List<Rol> m_Roles = new List<Rol>();
            Rol m_Rol = new Rol
            {
                IdRol = 1,
                NombreRol = "Rol ELiminado",
                Log = true,
                Configuracion = true
               
            };
            m_Roles.Add(m_Rol);
            m_Roles.Add(m_Rol);
            m_Roles.Add(m_Rol);
            ViewBag.ListaConfig = m_Roles; 
            ViewBag.MensajeSuccess = "Rol Eliminado";
            return PartialView("Index");
        }
    }
}

IHIConfig/Views/Rol/_Create.cshtml
@model Intecsus.Entidades.Rol
@using Intecsus.Entidades
@{

    string m_Formulario = string.IsNullOrEmpty(ViewBag.ConfigIHI) ? "Crear" : ViewBag.ConfigIHI;
}
@using (Ajax.BeginForm(@m_Formulario, "Configuracion",
    new AjaxOptions
    {
        OnBegin = "onSuccess",
        HttpMethod = "POST",
        UpdateTargetId = "Configurador",
        InsertionMode = InsertionMode.Replace,
        LoadingElementId = "divLoader"
    }))
{
    @Html.AntiForgeryToken()
    @Html.Partial("~/Views/Shared/_Mensajes.cshtml")
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.NombreRol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreRol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreRol, "", new { @class = "text-danger" })
                @Html.EditorFor(model => model.IdRol, new { htmlAttributes = new { @class = "invisible" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Configuracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Configuracion)
                    @Html.ValidationMessageFor(model => model.Configuracion, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Impresoras, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Impresoras)
                    @Html.ValidationMessageFor(model => model.Impresoras, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardFormat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CardFormat)
                    @Html.ValidationMessageFor(model => model.CardFormat, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Procesos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Procesos)
                    @Html.ValidationMessageFor(model => model.Procesos, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Log, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Log)
                    @Html.ValidationMessageFor(model => model.Log, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Transacciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Transacciones)
                    @Html.ValidationMessageFor(model => model.Transacciones, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Usuarios, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Usuarios)
                    @Html.ValidationMessageFor(model => model.Usuarios, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@m_Formulario" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IHIConfig/Views/Rol/_Details.cshtml
@model IEnumerable<Intecsus.Entidades.Rol>
@using Intecsus.Entidades
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NombreRol)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Configuracion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Impresoras)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CardFormat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Procesos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Log)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Transacciones)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Usuarios)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreRol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Configuracion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Impresoras)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CardFormat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Procesos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Log)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Transacciones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuarios)
            </td>
            <td>
                @Ajax.ActionLink("Editar", "Details", "Rol", item, new AjaxOptions
                                 {
                                     HttpMethod = "GET",
                                     UpdateTargetId = "divEditRol",
                                     InsertionMode = InsertionMode.Replace,
                                     LoadingElementId = "divLoader"
                                 })|
                @Ajax.ActionLink("Eliminar", "Delete", "Rol", new { idRol = item.IdRol }, new AjaxOptions
                                 {
                                     HttpMethod = "POST",
                                     UpdateTargetId = "divRol",
                                     InsertionMode = InsertionMode.Replace,
                                     LoadingElementId = "divLoader"
                                 })
            </td>
        </tr>
    }

</table>