IHIConfig/Controllers/EstadosXImpresionController.cs
using IHIConfig.Filtros;
using Intecsus.Entidades;
using System.Collections.Generic;
using System.Web.Mvc;

namespace IHIConfig.Controllers
{
    [Loging(Order = 1)]
    [LogErrors(Order = 2)]
    [HandleError(Order = 3)]
    public class EstadosXImpresionController : Controller
    {
        // GET: EstadosXImpresion
        public ActionResult Index()
        {
            //
            List<EstadoXImpresion> m_Estados = new List<EstadoXImpresion>();
            EstadoXImpresion m_Estado = new EstadoXImpresion
            {
                IdCodRespuesta = 1,
                IdDataInteger = "1",
                IdMessageType = "1",
                Estado = new Estados
                {
                    IdEstado = 1,
                    NombreEstado = "Prueba"
                }

            };
            m_Estados.Add(m_Estado);
            m_Estados.Add(m_Estado);
            m_Estados.Add(m_Estado);
            ViewBag.ListEstadoXImpresion = m_Estados;
            return View();
        }

        public PartialViewResult Details(EstadoXImpresion estadoImpresion)
        {
            ViewBag.EstadoXImpresion = "Modificar";
            return PartialView("_Create", estadoImpresion);
        }

        public PartialViewResult Create()
        {
            EstadoXImpresion m_EstadoImpresion = new EstadoXImpresion();
            m_EstadoImpresion.EstadosSelec = (IEnumerable<Estados>)Session["Estados"];
            return PartialView("_Create", m_EstadoImpresion);
        }

        [HttpPost]
        public PartialViewResult Crear(EstadoXImpresion estadoImpresion)
        {
            //OPTIMIZAR y validar si viene vacio para no ejecutar la operacion
            List<EstadoXImpresion> m_EstadosImpresion = new List<EstadoXImpresion>();

            m_EstadosImpresion.Add(estadoImpresion);
            m_EstadosImpresion.Add(estadoImpresion);
            m_EstadosImpresion.Add(estadoImpresion);
            ViewBag.ListEstadoXImpresion = m_EstadosImpresion;
            ViewBag.MensajeSuccess = "Parametro Creado";
            return PartialView("Index");
        }

        [HttpPost]
        public PartialViewResult Modificar(EstadoXImpresion estadoImpresion)
        {
            //OPTIMIZAR
            List<EstadoXImpresion> m_EstadosImpresion = new List<EstadoXImpresion>();
            m_EstadosImpresion.Add(estadoImpresion);
            m_EstadosImpresion.Add(estadoImpresion);
            m_EstadosImpresion.Add(estadoImpresion);
            ViewBag.ListEstadoXImpresion = m_EstadosImpresion;
            ViewBag.MensajeSuccess = "Parametro  Modificado";
            return PartialView("Index");
        }

        [HttpPost]
        public PartialViewResult Delete(int IdCodRespuesta)
        {
            //OPTIMIZAR
            List<EstadoXImpresion> m_Estados = new List<EstadoXImpresion>();
            EstadoXImpresion m_Estado = new EstadoXImpresion
            {
                IdCodRespuesta = 1,
                IdDataInteger = "1",
                IdMessageType = "1",
                Estado = new Estados
                {
                    IdEstado = 1,
                    NombreEstado = "Elimiancion"
                }
                
            };
            m_Estados.Add(m_Estado);
            m_Estados.Add(m_Estado);
            m_Estados.Add(m_Estado);
            ViewBag.ListEstadoXImpresion = m_Estados;
            ViewBag.MensajeSuccess = "Parametro  Eliminado";
            return PartialView("Index");
        }
    }
}

IHIConfig/Views/EstadosXImpresion/Index.cshtml
<h4 class="subTitulo text-center"> Estados X Impresión</h4>
<div class="col-sm-6 media" id="divListEstadoXImpresion">
    @Html.Partial("~/Views/EstadosXImpresion/_Details.cshtml", (List<Intecsus.Entidades.EstadoXImpresion>)ViewBag.ListEstadoXImpresion)
</div>
<div class="col-sm-5 media" id="divEditEstadoXImpresion">
    @{
        Intecsus.Entidades.EstadoXImpresion m_Estados = new Intecsus.Entidades.EstadoXImpresion();
        m_Estados.EstadosSelec = (IEnumerable<Intecsus.Entidades.Estados>)Session["Estados"];
    }
    @Html.Partial("~/Views/EstadosXImpresion/_Create.cshtml", m_Estados)
</div>

IHIConfig/Views/EstadosXImpresion/_Create.cshtml
@model Intecsus.Entidades.EstadoXImpresion
@using Intecsus.Entidades
@{

    string m_Formulario = string.IsNullOrEmpty(ViewBag.EstadoXImpresion) ? "Crear" : ViewBag.EstadoXImpresion;
}

@using (Ajax.BeginForm(@m_Formulario, "EstadosXImpresion",
    new AjaxOptions
    {
        OnBegin = "onSuccess",
        HttpMethod = "POST",
        UpdateTargetId = "divEstadoXImpresion",
        InsertionMode = InsertionMode.Replace,
        LoadingElementId = "divLoader"
    }))
{
    @Html.AntiForgeryToken()
    @Html.Partial("~/Views/Shared/_Mensajes.cshtml")
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2">
                @Model.IdCodRespuesta
                @Html.EditorFor(model => model.IdCodRespuesta, new { htmlAttributes = new { @class = "invisible" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdMessageType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdMessageType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdMessageType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdDataInteger, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdDataInteger, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdDataInteger, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(
                x => x.SelectedItemId,
       new SelectList(Model.EstadosSelec, "IdEstado", "NombreEstado"), "Selecciona un Estado",
              new { @class = "form-control" }
            )
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@m_Formulario" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IHIConfig/Views/EstadosXImpresion/_Details.cshtml
@model IEnumerable<Intecsus.Entidades.EstadoXImpresion>
@using Intecsus.Entidades
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdCodRespuesta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdMessageType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdDataInteger)
        </th>
        <th>
            Estado
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdCodRespuesta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdMessageType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdDataInteger)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado.NombreEstado)
            </td>
            <td>
                @Ajax.ActionLink("Editar", "Details", "EstadosXImpresion", item, new AjaxOptions
                                 {
                                     HttpMethod = "GET",
                                     UpdateTargetId = "divEditEstadoXImpresion",
                                     InsertionMode = InsertionMode.Replace,
                                     LoadingElementId = "divLoader"
                                 })|
                @Ajax.ActionLink("Eliminar", "Delete", "EstadosXImpresion", new { IdCodRespuesta = item.IdCodRespuesta }, new AjaxOptions
                                 {
                                     HttpMethod = "POST",
                                     UpdateTargetId = "divEstadoXImpresion",
                                     InsertionMode = InsertionMode.Replace,
                                     LoadingElementId = "divLoader"
                                 })
            </td>
        </tr>
    }

</table>