IHIConfig/Controllers/ConversionMController.cs
using IHIConfig.Filtros;
using Intecsus.Entidades;
using System.Collections.Generic;
using System.Web.Mvc;

namespace IHIConfig.Controllers
{
    [Loging(Order = 1)]
    [LogErrors(Order = 2)]
    [HandleError(Order = 3)]
    public class ConversionMController : Controller
    {
        // GET: ConversionM
        public ActionResult Index()
        {
            List<ConversionMensaje> m_Conversiones = new List<ConversionMensaje>();
            ConversionMensaje m_Conversion = new ConversionMensaje
            {
                CodigoCliente = "1234",
                IdConversion = 1,
                MensajeCW = "What is it??",
                Mensaje = "Prueba conversion"

            };

            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            ViewBag.ListaConversionM = m_Conversiones;
            return View();
        }

        public PartialViewResult Details(ConversionMensaje mensajesC)
        {
            ViewBag.ConversionM = "Modificar";
            return PartialView("_Create", mensajesC);
        }

        public PartialViewResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public PartialViewResult Crear(ConversionMensaje mensajesC)
        {
            //OPTIMIZAR  y validar si viene vacio para no ejecutar la operacion
            List<ConversionMensaje> m_Conversiones = new List<ConversionMensaje>();
            ConversionMensaje m_Conversion = new ConversionMensaje 
                                {
                                    CodigoCliente = "1234",
                                    IdConversion = 1,
                                    MensajeCW = "What is it??",
                                    Mensaje = "Prueba conversion creación"

                                };

            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            ViewBag.ListaConversionM = m_Conversiones;
            ViewBag.MensajeSuccess = "Conversión Creada";
            return PartialView("Index");
        }

        [HttpPost]
        public PartialViewResult Modificar(ConversionMensaje conversion)
        {
            //OPTIMIZAR
            List<ConversionMensaje> m_Conversiones = new List<ConversionMensaje>();
            ConversionMensaje m_Conversion = new ConversionMensaje
            {
                CodigoCliente = "1234",
                IdConversion = 1,
                MensajeCW = "What is it??",
                Mensaje = "Prueba conversion Editado"

            };

            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            ViewBag.ListaConversionM = m_Conversiones;
            ViewBag.MensajeSuccess = "Conversión Editado";
            return PartialView("Index");
        }

        [HttpPost]
        public PartialViewResult Delete(int idConversion)
        {
            //OPTIMIZAR 
            List<ConversionMensaje> m_Conversiones = new List<ConversionMensaje>();
            ConversionMensaje m_Conversion = new ConversionMensaje
            {
                CodigoCliente = "1234",
                IdConversion = 1,
                MensajeCW = "What is it??",
                Mensaje = "Prueba conversion Eliminado"

            };

            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            ViewBag.ListaConversionM = m_Conversiones;
            ViewBag.MensajeSuccess = "Conversión Eliminado";
            return PartialView("Index");
        }
    }
}

IHIConfig/Views/ConversionM/Index.cshtml
<h4 class="subTitulo text-center"> Conversión Mensajes</h4>
<div class="col-sm-6 media" id="divListConversionM">
    @Html.Partial("~/Views/ConversionM/_Details.cshtml", (List<Intecsus.Entidades.ConversionMensaje>)ViewBag.ListaConversionM)
</div>
<div class="col-sm-5 media" id="divEditConversionM">
    @Html.Partial("~/Views/ConversionM/_Create.cshtml", new Intecsus.Entidades.ConversionMensaje())
</div>

IHIConfig/Views/ConversionM/_Create.cshtml
@model Intecsus.Entidades.ConversionMensaje
@using Intecsus.Entidades
@{

    string m_Formulario = string.IsNullOrEmpty(ViewBag.ConversionM) ? "Crear" : ViewBag.ConversionM;
}

@using (Ajax.BeginForm(@m_Formulario, "ConversionM",
    new AjaxOptions
    {
        OnBegin = "onSuccess",
        HttpMethod = "POST",
        UpdateTargetId = "divConversiones",
        InsertionMode = InsertionMode.Replace,
        LoadingElementId = "divLoader"
    }))
{
    @Html.AntiForgeryToken()
    @Html.Partial("~/Views/Shared/_Mensajes.cshtml")
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2">
                @Model.IdConversion
                @Html.EditorFor(model => model.IdConversion, new { htmlAttributes = new { @class = "invisible" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MensajeCW, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MensajeCW, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MensajeCW, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mensaje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mensaje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mensaje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodigoCliente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodigoCliente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@m_Formulario" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IHIConfig/Views/ConversionM/_Details.cshtml
@model IEnumerable<Intecsus.Entidades.ConversionMensaje>
@using Intecsus.Entidades
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdConversion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MensajeCW)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mensaje)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodigoCliente)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdConversion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MensajeCW)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mensaje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodigoCliente)
            </td>
            <td>
                @Ajax.ActionLink("Editar", "Details", "ConversionM", item, new AjaxOptions
                                 {
                                     HttpMethod = "GET",
                                     UpdateTargetId = "divEditConversionM",
                                     InsertionMode = InsertionMode.Replace,
                                     LoadingElementId = "divLoader"
                                 })|
                @Ajax.ActionLink("Eliminar", "Delete", "ConversionM", new { idConversion = item.IdConversion }, new AjaxOptions
                                 {
                                     HttpMethod = "POST",
                                     UpdateTargetId = "divConversiones",
                                     InsertionMode = InsertionMode.Replace,
                                     LoadingElementId = "divLoader"
                                 })
            </td>
        </tr>
    }

</table>