IHIConfig/Controllers/ConfiguracionController.cs
using IHIConfig.Filtros;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Intecsus.Entidades;

namespace IHIConfig.Controllers
{
    [Loging(Order = 1)]
    [LogErrors(Order = 2)]
    [HandleError(Order = 3)]
    public class ConfiguracionController : Controller
    {
        // GET: Configuracion
        public ActionResult Index()
        {
            List<Configurar> m_ListConfigurar = new List<Configurar>();
            //Capa negocio
            Configurar m_Config = new Configurar
            {
                IDValor = "1",
                Valor = "Pruebas",
                TipoDato = "Cadena"
            };
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            ViewBag.ListaConfig = m_ListConfigurar;
            return View("Index");
        }

        // GET: Configuracion/Details
        public PartialViewResult Details(Configurar configurar)
        {
            ViewBag.ConfigIHI = "Modificar";
            return PartialView("_Create", configurar);
        }

        // GET: Configuracion/Create
        public PartialViewResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public PartialViewResult Crear(Configurar config)
        {
            //OPTIMIZAR y validar si viene vacio para no ejecutar la operacion
            List<Configurar> m_Configs = new List<Configurar>();
            Configurar m_Config = new Configurar
            {
                IDValor = "1",
                Valor = "Pruebas Creacion",
                TipoDato = "Cadena"
            };
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            ViewBag.ListaConfig = m_Configs;
            ViewBag.MensajeSuccess = "Parametro de configuración Creado";
            return PartialView("Index");
        }

        [HttpPost]
        public PartialViewResult Modificar(Configurar config)
        {
            //OPTIMIZAR
            List<Configurar> m_Configs = new List<Configurar>();
            Configurar m_Config = new Configurar
            {
                IDValor = "1",
                Valor = "Pruebas Edición",
                TipoDato = "Cadena"
            };
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            ViewBag.ListaConfig = m_Configs;
            ViewBag.MensajeSuccess = "Parametro de configuración Modificado";
            return PartialView("Index");
        }

        [HttpPost]
        public PartialViewResult Delete(int idConfig)
        {
            //OPTIMIZAR
            List<Configurar> m_Configs = new List<Configurar>();
            Configurar m_Config = new Configurar
            {
                IDValor = "1",
                Valor = "Pruebas Eliminacion",
                TipoDato = "Cadena"
            };
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            m_Configs.Add(m_Config);
            ViewBag.ListaConfig = m_Configs;
            ViewBag.MensajeSuccess = "Parametro de configuración Eliminado";
            ViewBag.Informativo = "Se aconseja NO eliminar los parametros ya que afectara el funcionamiento del IHI";
            return PartialView("Index");
        }
    }
}

IHIConfig/Controllers/MensajesController.cs
using IHIConfig.Filtros;
using Intecsus.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IHIConfig.Controllers
{
    [Loging(Order = 1)]
    [LogErrors(Order = 2)]
    [HandleError(Order = 3)]
    public class MensajesController : Controller
    {
        // GET: Mensajes
         [OutputCache(Duration = 50)]
        public ActionResult Index()
        {
            List<Mensajes> m_Mensajes = new List<Mensajes>();
            Mensajes m_Mensaje = new Mensajes
            {
                CodigoCliente = "123",
                CodigoMensaje = "1234",
                MensajeEnviado = "Prueba mensajes"

            };
            m_Mensajes.Add(m_Mensaje);
            m_Mensajes.Add(m_Mensaje);
            m_Mensajes.Add(m_Mensaje);
            ViewBag.ListaMensajes = m_Mensajes;
            return View();
        }

         public PartialViewResult Details(Mensajes mensaje)
         {
             ViewBag.Mensajes = "Modificar";
             return PartialView("_Create", mensaje);
         }

         public PartialViewResult Create()
         {
             return PartialView("_Create");
         }

         [HttpPost]
         public PartialViewResult Crear(Mensajes mensaje)
         {
             //OPTIMIZAR  y validar si viene vacio para no ejecutar la operacion
             List<Mensajes> m_Mensajes = new List<Mensajes>();
             Mensajes m_Mensaje = new Mensajes
                {
                    CodigoCliente = "123",
                    CodigoMensaje = "1234",
                    MensajeEnviado = "Prueba mensajes Creado"
             
                };
             m_Mensajes.Add(m_Mensaje);
             m_Mensajes.Add(m_Mensaje);
             m_Mensajes.Add(m_Mensaje);
             ViewBag.ListaMensajes = m_Mensajes;
             ViewBag.MensajeSuccess = "Mensaje Creado";
             return PartialView("Index");
         }

         [HttpPost]
         public PartialViewResult Modificar(Mensajes mensaje)
         {
             //OPTIMIZAR
             List<Mensajes> m_Mensajes = new List<Mensajes>();
             Mensajes m_Mensaje = new Mensajes
             {
                 CodigoCliente = "123",
                 CodigoMensaje = "1234",
                 MensajeEnviado = "Prueba mensajes Editado"

             };
             m_Mensajes.Add(m_Mensaje);
             m_Mensajes.Add(m_Mensaje);
             m_Mensajes.Add(m_Mensaje);
             ViewBag.ListaMensajes = m_Mensajes;
             ViewBag.MensajeSuccess = "Mensaje Editado";
             return PartialView("Index");
         }

         [HttpPost]
         public PartialViewResult Delete(int codigoMensaje)
         {
             //OPTIMIZAR 
             List<Mensajes> m_Mensajes = new List<Mensajes>();
             Mensajes m_Mensaje = new Mensajes
             {
                 CodigoCliente = "123",
                 CodigoMensaje = "1234",
                 MensajeEnviado = "Prueba mensajes Elimidado"

             };
             m_Mensajes.Add(m_Mensaje);
             m_Mensajes.Add(m_Mensaje);
             m_Mensajes.Add(m_Mensaje);
             ViewBag.ListaMensajes = m_Mensajes;
             ViewBag.MensajeSuccess = "Mensaje Elimidado";
             return PartialView("Index");
            
         }
    }
}

IHIConfig/Controllers/PrincipalesController.cs
using IHIConfig.Filtros;
using Intecsus.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IHIConfig.Controllers
{
    [Loging(Order = 1)]
    [LogErrors(Order = 2)]
    [HandleError(Order = 3)]
    public class PrincipalesController : Controller
    {
        [OutputCache(Duration = 40)]
        public ActionResult Configuracion()
        {
            List<Configurar> m_ListConfigurar = new List<Configurar>();
            //Lo debe traer la capa de negocio 
            //Config
            Configurar m_Config = new Configurar
            {
                IDValor = "1",
                Valor = "Pruebas",
                TipoDato = "Cadena"
            };
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            m_ListConfigurar.Add(m_Config);
            ViewBag.ListaConfig = m_ListConfigurar;
            //OPTIMIZAR EstadosXimpresion
            List<ProcesosBD> m_procesos = new List<ProcesosBD>();
            ProcesosBD m_Proceso = new ProcesosBD();
            m_Proceso.IDProceso = 1;
            m_Proceso.NombreProceso = "Proceso Prueba";
            m_procesos.Add(m_Proceso);
            m_procesos.Add(m_Proceso);
            m_procesos.Add(m_Proceso);
            ViewBag.ListaProcesos = m_procesos;
            return View();
        }

        [OutputCache(Duration = 40)]
        public ActionResult IntegracionCW()
        {
            //Impresoras
            List<Impresora> m_Impresoras = new List<Impresora>();
            Impresora m_Impresora = new Impresora
            {
                IdImpresora = 1,
                NombreRecibido = "PruebaEnvio",
                PCNAME = "Prueba",
                IP = "192.10.10.1"
            };
            m_Impresoras.Add(m_Impresora);
            m_Impresoras.Add(m_Impresora);
            m_Impresoras.Add(m_Impresora);
            ViewBag.ListaImpresoras = m_Impresoras;
            //Productos
            //OPTIMIZAR
            List<Producto> m_Productos = new List<Producto>();
            Producto m_Producto = new Producto
            {
                IdProducto = 1,
                ProductoName = "Producto Prueba",
                CardName = "Pruebas",
                Cliente = "Prueba",
                XML = @"<Parametros>
                                  <Parametro nombre='@PAN@'  tipo='String' codifica='SI' derecha='5' izquierda='3' >
                                    <Valor inicio='63' tamano='16' ISPCI='TRUE' ValoresS='/RespuestaRealceEmisionTarjetasDTO/trackIField/panField'  ></Valor>
                                  </Parametro>
                                  <Parametro nombre='@CardHolderName@'  tipo='String' codifica='NO'>
                                    <Valor inicio='38' tamano='40'  ISPCI='TRUE'  ValoresS='/RespuestaRealceEmisionTarjetasDTO/nombreCompletoField'></Valor>
                                  </Parametro>
                                  <Parametro nombre='@TIPODOCUMENTO1@'  tipo='String' codifica='NO'>
                                    <Valor inicio='38' tamano='2' ValoresS='/RespuestaRealceEmisionTarjetasDTO/tipoIdentificacionAField'></Valor>
                                  </Parametro>
                                </Parametros>",
                Tamano = 200
            };
            m_Productos.Add(m_Producto);
            m_Productos.Add(m_Producto);
            m_Productos.Add(m_Producto);
            Session["ListaProductos"] = m_Productos;
            //Conversiones
            List<ConversionMensaje> m_Conversiones = new List<ConversionMensaje>();
            ConversionMensaje m_Conversion = new ConversionMensaje
            {
                CodigoCliente = "1234",
                IdConversion = 1,
                MensajeCW = "What is it??",
                Mensaje = "Prueba conversion"

            };

            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            ViewBag.ListaConversionM = m_Conversiones;
            return View();
        }

        [OutputCache(Duration = 40)]
        public ActionResult Mensajes()
        {
            //Mensajes
            List<Mensajes> m_Mensajes = new List<Mensajes>();
            Mensajes m_Mensaje = new Mensajes
            {
                CodigoCliente = "123",
                CodigoMensaje = "1234",
                MensajeEnviado = "Prueba mensajes"

            };
            m_Mensajes.Add(m_Mensaje);
            m_Mensajes.Add(m_Mensaje);
            m_Mensajes.Add(m_Mensaje);
            ViewBag.ListaMensajes = m_Mensajes;

            //Conversiones
            List<ConversionMensaje> m_Conversiones = new List<ConversionMensaje>();
            ConversionMensaje m_Conversion = new ConversionMensaje
            {
                CodigoCliente = "1234",
                IdConversion = 1,
                MensajeCW = "What is it??",
                Mensaje = "Prueba conversion"

            };

            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            m_Conversiones.Add(m_Conversion);
            ViewBag.ListaConversionM = m_Conversiones;
            return View();
        }

        [OutputCache(Duration = 40)]
        public ActionResult EstadosCW()
        {
            //Estados
            if (Session["Estados"] == null)
            {
                List<Estados> m_Estados = new List<Estados>();
                Estados m_Estado = new Estados
                {
                    IdEstado = 1,
                    NombreEstado = "Estado Inicio"
                };
                m_Estados.Add(m_Estado);
                 m_Estado = new Estados
                {
                    IdEstado = 2,
                    NombreEstado = "Estado Prueba"
                };
                m_Estados.Add(m_Estado);
                m_Estado = new Estados
                {
                    IdEstado = 2,
                    NombreEstado = "Estado Tercero"
                };
                m_Estados.Add(m_Estado);
                Session["Estados"] = m_Estados;
            }

            //COnversion Estado X Impresora

            List<EstadoXImpresoraC> m_EstadosXImpresora = new List<EstadoXImpresoraC>();
            EstadoXImpresoraC m_EstadoxImpresora = new EstadoXImpresoraC
            {
                IdCodRespuesta = 1,
                DeviceStatus = "1",
                DeviceType = "1",
                ReturnCode = "1",
                Estado = new Estados
                {
                    IdEstado = 1,
                    NombreEstado = "PruebaInicial"
                }

            };


            m_EstadosXImpresora.Add(m_EstadoxImpresora);
            m_EstadosXImpresora.Add(m_EstadoxImpresora);
            m_EstadosXImpresora.Add(m_EstadoxImpresora);
            ViewBag.ListaEstadoXImpresora = m_EstadosXImpresora;
            //Conversiones x Impresion
            List<EstadoXImpresion> m_EstadosXImpresion = new List<EstadoXImpresion>();
            EstadoXImpresion m_EstadoXImpresion = new EstadoXImpresion
            {
                IdCodRespuesta = 1,
                IdDataInteger = "1",
                IdMessageType = "1",
                Estado = new Estados
                {
                    IdEstado = 1,
                    NombreEstado = "Prueba"
                }

            };
            m_EstadosXImpresion.Add(m_EstadoXImpresion);
            m_EstadosXImpresion.Add(m_EstadoXImpresion);
            m_EstadosXImpresion.Add(m_EstadoXImpresion);
            ViewBag.ListEstadoXImpresion = m_EstadosXImpresion;
            return View();
        }

        [OutputCache(Duration = 40)]
        public ActionResult UsuariosCW()
        {
            UsuarioC m_User = (UsuarioC)Session["Usuario"];
            if (m_User.RolAsociado.Usuarios == true) 
            {
                List<UsuarioC> m_ListUsuario = new List<UsuarioC>();
                //Capa negocio
                UsuarioC user = new UsuarioC();
                user.Nombre = "Andres";
                user.Apellido = "Roldan";
                user.Identificacion = "123456";
                user.RolAsociado = new Rol();
                user.RolAsociado.IdRol = 1;
                user.RolAsociado.NombreRol = "Admin";
                user.RolAsociado.Configuracion = true;
                m_ListUsuario.Add(user);
                m_ListUsuario.Add(user);
                m_ListUsuario.Add(user);
                m_ListUsuario.Add(user);
                m_ListUsuario.Add(user);
                m_ListUsuario.Add(user);
                ViewBag.ListUsuarios = m_ListUsuario;
            }
            //Roles
           
            ViewBag.ListRoles = m_User.Roles;

            return View();
        }
    }
}

IHIConfig/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IHI</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="40">
    <div class="jumbotron Titulo text-center">

        <h1><strong>I</strong>ntecsus <strong>H</strong>ost <strong>I</strong>nterface</h1>
        <p>Sitio Web para edición y configuración</p>
        @RenderBody()
    </div>
    @Html.Partial("_Mensajes")
    <div class="container-fluid" id="about">
        <div class="row">
            <div class="col-sm-8">
                <h2>Acerca del Intecsus Host Interface</h2>
                <h4>Es una solución tecnologica compuesta por varias aplicacione.</h4>
                <p>Su funcion principal es lograr la interacción con diferentes sistemas con el objetivo de realizar todo el proceso de emisión instantanea de tarjetas</p>
            </div>
            <div class="col-sm-4 media">
                <span class="glyphicon glyphicon-signal logoP" style="font-size: 150px;"> </span>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-grey" id="portfolio">
        <div class=" row">
            <div class="col-sm-4 media">
                <span class="glyphicon glyphicon-globe logoP" style="font-size: 150px;"></span>
            </div>
            <div class="col-sm-8">
                <h2>Implementaciones</h2>
                <h4>La solucion ha sido implementada por entidades financieras en toda latinoamerica</h4>
                <p>Logrando cumplir con los objetivos de facilitar los procesos para que el cliente tenga ......</p>
            </div>
        </div>
    </div>
    <div class="container-fluid text-center" id="services">
        <h2>Servicios</h2>
        <br>
        <div class="row">
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-off logo-smallP"></span>
                <h4>Funcionamiento</h4>
                <p>Las 24 horas de todos los días del año</p>
            </div>
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-user logo-smallP"></span>
                <h4>Usuarios</h4>
                <p>Obtienen su tarjeta en tiempo inmediato</p>
            </div>
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-lock logo-smallP"></span>
                <h4>JOB DONE</h4>
                <p>Lorem ipsum dolor sit amet..</p>
            </div>
        </div>
        <br><br>
        <div class="row">
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-ok logo-smallP"></span>
                <h4>GREEN</h4>
                <p>Lorem ipsum dolor sit amet..</p>
            </div>
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-certificate logo-smallP"></span>
                <h4>Area tecnica</h4>
                <p>caa</p>
            </div>
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-wrench logo-smallP"></span>
                <h4>HARD WORK</h4>
                <p>Lorem ipsum dolor sit amet..</p>
            </div>
        </div>
    </div>
    <div class="container-fluid " id="PRICING">
        <h2>What our customers say</h2>
        <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <h4>"This company is the best. I am so happy with the result!"<br><span style="font-style:normal;">Michael Roe, Vice President, Comment Box</span></h4>
                </div>
                <div class="item">
                    <h4>"One word... WOW!!"<br><span style="font-style:normal;">John Doe, Salesman, Rep Inc</span></h4>
                </div>
                <div class="item">
                    <h4>"Could I... BE any more happy with this company?"<br><span style="font-style:normal;">Chandler Bing, Actor, FriendsAlot</span></h4>
                </div>
            </div>
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="container-fluid bg-grey text-center" id="contact">
        <h2>CONTACT</h2>
        <div>
            <p>Contact us and we'll get back to you within 24 hours.</p>
            <p><span class="glyphicon glyphicon-map-marker"></span> Chicago, US</p>
            <p><span class="glyphicon glyphicon-phone"></span> +00 1515151515</p>
            <p><span class="glyphicon glyphicon-envelope"></span> myemail@something.com</p>
        </div>
    </div>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">
                    Bienvenido
                </div>
                @*<a class="navbar-brand" href="#"><img src="~/Img/LOGOIntecsus.png" alt="Intecsus SAS" width="30" height="30" /></a>*@
            </div>
            <div class="navbar-collapse collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#about">ABOUT</a></li>
                    <li><a href="#portfolio">PORTFOLIO</a></li>
                    <li><a href="#services">SERVICES</a></li>
                    <li><a href="#pricing">PRICING</a></li>
                    <li><a href="#contact">CONTACT</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <footer class="text-center">
        <p>&copy; @DateTime.Now.Year - INTECSUS SAS</p>
        <p>Diseñado y desarrollado por AERM</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

IHIConfig/Views/Shared/_LayoutPrincipal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IHI</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="40">
    <div class="jumbotron Titulo text-center">

        <h1><strong>I</strong>ntecsus <strong>H</strong>ost <strong>I</strong>nterface</h1>
        <p>Sitio Web para edición y configuración</p>
    </div>
    @Html.Partial("_Menu")
    @Html.Partial("_Mensajes")
    @RenderBody()
    <footer class="text-center">
        <p>&copy; @DateTime.Now.Year - INTECSUS SAS</p>
        <p>Diseñado y desarrollado por AERM</p>
    </footer>

    <div id="divLoader" style="display: none;">
        <div id="divLodModal" class="modal"></div>
        <div id="divFondo" class="loader">
            <img id=" imgloader" src="~/img/cargando-loading.gif" alt="Cargando ..." />
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/ajax")
    @Scripts.Render("~/bundles/sitio")
    @Scripts.Render("~/bundles/Filtros")
    @RenderSection("scripts", required: false)
</body>
</html>

IHIConfig/Views/Shared/_Mensajes.cshtml
@{
    if (String.IsNullOrEmpty(ViewBag.MensajeError) == false)
    {
        <div class="alert alert-danger margin-bottom-0" role="alert">
            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            @ViewBag.MensajeError
        </div>
    }
    if (String.IsNullOrEmpty(ViewBag.MensajeSuccess) == false)
    {
        <div class="alert alert-success margin-bottom-0" role="alert">
            <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span>
            <span class="sr-only">Exitoso:</span>
            @ViewBag.MensajeSuccess
        </div>
    }
    if (String.IsNullOrEmpty(ViewBag.Informativo) == false)
    {
        <div class="alert alert-info margin-bottom-0" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Recuerde:</span>
            @ViewBag.Informativo
        </div>
    }
    if (String.IsNullOrEmpty(ViewBag.Advertencia) == false)
    {
        <div class="alert alert-warning margin-bottom-0" role="alert">
            <span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span>
            <span class="sr-only">Advertencia:</span>
            @ViewBag.Informativo
        </div>
    }
}

IHIConfig/Views/Shared/_Menu.cshtml
@*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @{
                    var user = (Intecsus.Entidades.Usuario)Session["Usuario"];
                    if (user != null)
                    {
                        <a class="navbar-brand" href="#myPage">@user.Nombres</a>
                    }
                }
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#about">ABOUT</a></li>
                    <li><a href="#services">SERVICES</a></li>
                    <li><a href="#portfolio">PORTFOLIO</a></li>
                    <li><a href="#pricing">PRICING</a></li>
                    <li><a href="#contact">CONTACT</a></li>
                </ul>
            </div>
        </div>
    </div>*@
<nav class="navbar navbar-default MenuEstatico">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        @{
            var user = (Intecsus.Entidades.Usuario)Session["Usuario"];
            if (user != null)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @{
                if (user.RolAsociado.Configuracion)
                {
                    <li>@Html.ActionLink("Configuración ", "Configuracion", "Principales")</li>
                }
                @*<li>@Html.ActionLink("Impresoras", "About", "Home")</li>
                    <li>@Html.ActionLink("CardFormat", "Contact", "Home")</li>*@
                            <li>@Html.ActionLink("Integración CW ", "IntegracionCW", "Principales")</li>
                            <li>@Html.ActionLink("Mensajes Cliente ", "Mensajes", "Principales")</li>
                            <li>@Html.ActionLink("Log Eventos", "About", "Home")</li>
                            <li>@Html.ActionLink("Transacciones", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Re-Procesos ", "IntegracionCW", "Principales")</li>
                            <li>@Html.ActionLink("Estados CW", "EstadosCW", "Principales")</li>
                            <li>@Html.ActionLink("Usuarios", "UsuariosCW", "Principales")</li>
                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Salir", "LogOn", "Home")</li>
                    </ul>
                </div>
            }
        }
    </div>
</nav>